### ISSUE TITLE
Assistance needed

### ISSUE THREAD

**Issue by PhillipFish** [cumulusmx/CumulusMX#129]
I am in need of assistance. More spesificallt with getting logged into the raspberry pi image with CumulusMX preinstalled.

I am asked for a username and passwordon startup,  which I assume is the same as for the CumulusMX boards, but it has been 48hours and I still have not recieved any activation code (checked spam as well) and have not heard anything back from site admins. Please help, I've run out of options on where to get help, this is my last resort.

Phil

**Comment by PhillipFish** [comment]
Missed that. Thank you.

**Comment by HansR00** [comment]
In general, the idea is to get support on [the forum](https://cumulus.hosiene.co.uk/index.php), not on the github repository.

**Comment by PhillipFish** [comment]
HansR00, thanks, yes i know that. I registered on the site 3 days ago....I am still waiting for the activation email and have already contacted site admins twice and no word back from them either. This was my last option to try and get help. If I was able to use the forum, I would've done that instead.
