### ISSUE TITLE
Problems with Docker and Cumulus.ini rewrite

### ISSUE THREAD

**Issue by geduxas** [cumulusmx/CumulusMX#180]
Hi, I am trying to use Cumulus with Docker, and I am trying to keep cumulus.ini file outside of container. Because file in Docker container is mounted, Cumulus will lose ability's to delete it.. but it have possibility to modify. I think this place could be modified, to rewrite cumulus.ini file instead of deleting it all.. 

https://github.com/cumulusmx/CumulusMX/blob/71d9750fe08e22ff9e0f23e0a4eaaaa6bde2b108/CumulusMX/Cumulus.cs#L5845C1-L5854C5

**Comment by geduxas** [comment]
Just now noticed issue duplicate for closed #176 

I think my purpose could be better implemented for docker use. Yes if you map file to docker, CumulusMX will lose ability to recreate config file.. 
Is there any reason to delete file physically instead of rewriting full content?

**Comment by mcrossley** [comment]
Fix for you in the next release - v3.27.1

**Comment by geduxas** [comment]
Thank you @mcrossley everything works nice now :)
