### ISSUE TITLE
Additional steps to compile and run from source

### ISSUE THREAD

**Issue by Lux44** [cumulusmx/CumulusMX#26]
To compile from source I had to install [dotConnect for MySQL Express](https://www.devart.com/dotconnect/mysql/download.html).

To run I had to make 2 empty folders under CumulusMX-DistributionFiles: MXdiags and data.

Windows 1809, VS 2019.

**Comment by mcrossley** [comment]
I have added the empty folders to the DistributionFiles, I'll take a look at that dependency, I did not have to install it.

**Comment by Lux44** [comment]
Devart.Data [nuget package requires .NETStandard 1.3 or 2.0.](https://www.nuget.org/packages/Devart.Data/) CumulusMX targets Full framework 4.5.2. 

CumulusMX could be retargeted for 4.6.1 ([NETStandard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)), then Devart.Data and Devart.Data.MySql could be added as nuget packages. Both are currently missing from packages.config.

**Comment by mcrossley** [comment]
Is this issue closed now?

**Comment by mcrossley** [comment]
No response, closing issue
