### ISSUE TITLE
Upgrade of CumulusMX to latest libraries

### ISSUE THREAD

**Issue by HansR00** [cumulusmx/CumulusMX#30]
It appears impossible to make CMX straight from the current repository. Devart libraries are missing and many others are outdated. 

It seems correct to me to upgrade everything to the latest version and publish a CMX with those libraries. I assume in the end it will be necessary to be able to match all developments in the OS, .NET and Mono environments. I assume backwards compatibility will be supplied by the OS and the libraries.

I am currently working on it, is there any interest?

**Comment by mcrossley** [comment]
There is only one dependency missing - the Devart.Data.MySql.dll
The move that to the nuget package requires the Devart.Data and Devart.Data.MySql packages to be added.

I will do this for the next release (already built and under initial testing), but note it does mean that Cumulus MX distribution will increase in size considerably as those packages require a significant number of new system packages that are not currently distributed.

Chasing the latest versions of all the packages for the sake of it is a thankless task, and requires considerable effort to regression test each update. I am only updating packages when required to fix issues or for platform compatibility.

**Comment by HansR00** [comment]
> There is only one dependency missing - the Devart.Data.MySql.dl

Not completely true. I also ran into trouble with the unosquare libraries as well (the webserver thing). Especially the EmbedIO seems to have split off and the using statement did not work anymore. Could not get it working quickly, doid not understand properly what had happened. Some care must be taken there I think.

**Comment by HansR00** [comment]
As from 3.2.0 this has been solved. I can now make CumulusMX after a fetch on my own machine.
