### ISSUE TITLE
Davis Station not downloading historic logger data in b3088

### ISSUE THREAD

**Issue by dhover** [cumulusmx/CumulusMX#80]
After stopping MX for 10 minutes the historic data is not downloaded.
I'm using a Davis Vantage Pro 2 in combination with an Weather Envoy.

**Comment by mcrossley** [comment]
Please ask support type questions on the support forum: [Cumulus Support](https://cumulus.hosiene.co.uk)

**Comment by dhover** [comment]
You may close this issue.
